#! /usr/bin/bash

mediatitle() {
    op=~/.config/currentmedia
    sts="$(awk '$1~"status"{print $2}' "$op")"
    art="$(awk '$1~"artist"{for (i=2; i<=NF; i++) printf " " $i}' "$op")"
    ttl="$(awk '$1~"title"{for (i=2; i<=NF; i++) printf " " $i}' "$op")"
    
    case "$sts" in
      "[playing]") [[ -n $art ]] && echo "[>>$art:$ttl" || echo "[>>$ttl";;
      "[paused]") [[ -n $art ]] && echo "[||$art:$ttl" || echo "[||$ttl";;
      *) echo " [|]"
    esac
}

scroll() {
    killall scroller 2>/dev/null
    scroller -b "|" -t "$(mediatitle)" -e "|"
}

scroll
trap scroll SIGHUP 

while true; do read -r; done
