#! /usr/bin/bash

declare PID

mediatitle() {
    op="$HOME/.config/currentmedia"
    sts="$(awk '$1~"status"{print $2}' "$op")"
    art="$(awk '$1~"artist"{for (i=2; i<=NF; i++) printf " " $i}' "$op")"
    ttl="$(awk '$1~"title"{for (i=2; i<=NF; i++) printf " " $i}' "$op")"
    
    case "$sts" in
      "play") [[ -n $art ]] && echo "$art:$ttl" || echo "$ttl";;
      "pause") [[ -n $art ]] && echo "$art:$ttl" || echo "$ttl";;
      *) echo " "
    esac
}

scroll() {
    [[ -n $PID ]] && {
	kill "$PID" 2>/dev/null
        PID=""
    }
    scroller -b "|" -t "$(mediatitle)" -e "|" &
    PID=$!
}

scroll
trap '{ kill $PID 2>/dev/null; }' EXIT
trap scroll SIGHUP

while true; do read -r; done
