#! /usr/bin/bash

#######################################
#                                _    #
#  _ __ ___  _ __   _____      _| |_  #
# | '_ ` _ \| '_ \ / __\ \ /\ / / __| #
# | | | | | | |_) | (__ \ V  V /| |_  #
# |_| |_| |_| .__/ \___| \_/\_/  \__| #
#           |_|                       #
#######################################

MEDIAFILE="$HOME/.config/currentmedia"
declare PID

read_media() {
    local S A T msg
    S="$(awk '$1=="status" {print $2}' "$MEDIAFILE")"
    A="$(awk '$1=="artist" {$1=""; print}' "$MEDIAFILE")"
    T="$(awk '$1=="title" {$1=""; print}' "$MEDIAFILE")"
    A="${A/ /""}"
    case "$S" in
	play)  S="";;
	pause) S="";;
	*)     S=""
    esac
    msg="$(printf '%s:%s' "$A" "$T")"
    [[ -n $PID ]] && 
	ps --no-header --pid "$PID" && kill "$PID"
    scroller -b "| $S" -t "$msg" -e " |" &
    PID=$!
}

read_media
trap '{ kill $PID 2>/dev/null; }' EXIT
while read -r; do read_media; done< <(entr -p date <<< "$MEDIAFILE")
